version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: marketing-api-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: marketing
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend-network
volumes:
  mysql-data:

networks:
  backend-network:
    driver: bridge
